### ISSUE TITLE
Default values for fields in records table

### ISSUE THREAD

**Issue by fabiorauber** [allegro/django-powerdns-dnssec#105]
The application does not define default MySQL values for fields in the "records" table, preventing PowerDNS from working as a slave of another DNS server and writing to this table.

**Comment by fabiorauber** [comment]
Happens with _cryptokeys_ table also, preventing import of keys with _pdnssec import-zone-key_

**Comment by mzdeb** [comment]
Sorry, this project is not maintained anymore.
